//
//  StyleKit.m
//  OverDue Task List
//
//  Created by Nikki Durkin on 9/30/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKit.h"


@implementation StyleKit

#pragma mark Cache

static UIColor* _green = nil;
static UIColor* _orange = nil;
static UIColor* _red = nil;
static UIColor* _darkGrey = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _green = [UIColor colorWithRed: 0.478 green: 0.675 blue: 0.306 alpha: 1];
    _orange = [UIColor colorWithRed: 0.961 green: 0.651 blue: 0.137 alpha: 1];
    _red = [UIColor colorWithRed: 0.929 green: 0.443 blue: 0.38 alpha: 1];
    _darkGrey = [UIColor colorWithRed: 0.29 green: 0.29 blue: 0.29 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)green { return _green; }
+ (UIColor*)orange { return _orange; }
+ (UIColor*)red { return _red; }
+ (UIColor*)darkGrey { return _darkGrey; }

#pragma mark Drawing Methods

+ (void)drawCanvas1;
{
}

@end
