//
//  StyleKit.h
//  OverDue Task List
//
//  Created by Nikki Durkin on 9/30/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKit : NSObject

// Colors
+ (UIColor*)green;
+ (UIColor*)orange;
+ (UIColor*)red;
+ (UIColor*)darkGrey;

// Drawing Methods
+ (void)drawCanvas1;

@end
